---
version: "2"
checks:
  enabled: true
  method-count:
    config:
      threshold: 30
  argument-count:
    config:
      threshold: 5
exclude_patterns:
  - "build/"
  - "docs/"
  - "test/"
  - "bin/"
  - "testing/"
  - "runtest.py"
plugins:
  pep8:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false
