version: '3'
services:
  codeclimate:
    image: codeclimate/codeclimate
    environment:
      - CODECLIMATE_CODE=${PWD}
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/cc:/tmp/cc
    working_dir: /code
